### ISSUE TITLE
Rails 4 wrong number of arguments when calling .all on record

### ISSUE THREAD

**Issue by rchekaluk** [jeffp/enumerated_attribute#66]
Reference http://stackoverflow.com/questions/18553013/wrong-number-of-arguments-when-calling-all-on-record-which-has-enum-attr

```
$ rake db:seed
rake aborted!
wrong number of arguments (2 for 1)
REDACT/enumerated_attribute/lib/enumerated_attribute/integrations/active_record.rb:74:in `instantiate'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/querying.rb:45:in `block in find_by_sql'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/result.rb:21:in `block in each'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/result.rb:21:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/result.rb:21:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/querying.rb:45:in `map'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/querying.rb:45:in `find_by_sql'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/relation.rb:585:in `exec_queries'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/relation.rb:471:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/relation.rb:220:in `to_a'
REDACT/db/seeds.rb:17:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:214:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/engine.rb:540:in `load_seed'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/tasks/database_tasks.rb:154:in `load_seed'
/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.0.3/lib/active_record/railties/databases.rake:181:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by rchekaluk** [comment]
https://github.com/rails/rails/commit/9bcb9cd55f92fb0252b3ab93d068e0b336727af0#diff-3a78900604b345c3b1fec1156f23f43a
